-- 보호 시작일보다 입양일이 더 빠른 동물의 아이디와 이름을 조회
-- ANIMAL_INS . DATETIME > ANIMAL_OUTS .DATETIME
--날짜 빠른 순으 ..ASC
SELECT O.ANIMAL_ID,O.NAME 
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID =O.ANIMAL_ID
WHERE O.DATETIME < I.DATETIME
ORDER BY I.DATETIME ASC;