-- Python이나 C# 스킬을 가진 개발자
SELECT ID,EMAIL,FIRST_NAME,LAST_NAME
FROM DEVELOPERS 
WHERE SKILL_CODE  & (SELECT CODE FROM SKILLCODES WHERE NAME='Python')
    OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME='C#')
ORDER BY ID ASC;